version: "3"

services:
  codeserver:
    environment:
      PASSWORD: ${PASSWORD}
      DOMAIN: ${DOMAIN}
    expose:
      - 8443
    command: --allow-http --disable-telemetry
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      DOMAIN: ${DOMAIN}
    command: >
      /bin/sh -c 'envsubst "$$DOMAIN" < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && 
      nginx -g "daemon off;"'
    depends_on:
      - codeserver
